name: C++ CI

on: [push, pull_request]

env:
  TEST_STATUS: 0

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install dependencies
      run: sudo apt-get install -y g++
    - name: build
      run: |
        cd HCMUS-BigInt/build
        cmake CMakeLists.txt
        make

    - name: Run Add Test Case
      run: |
        cd HCMUS-BigInt/build
        ./HCMUS-BigInt-Test ../../CreateTestCaseBigInt/data/add.txt || echo "Add Test Case failed" >> $GITHUB_ENV && echo "TEST_STATUS=1" >> $GITHUB_ENV
      continue-on-error: true
  
    - name: Run Sub Test Case
      run: |
        cd HCMUS-BigInt/build
        ./HCMUS-BigInt-Test ../../CreateTestCaseBigInt/data/sub.txt || echo "Sub Test Case failed" >> $GITHUB_ENV && echo "TEST_STATUS=1" >> $GITHUB_ENV
      continue-on-error: true

    - name: Run Mul Test Case
      run: |
        cd HCMUS-BigInt/build
        ./HCMUS-BigInt-Test ../../CreateTestCaseBigInt/data/mul.txt || echo "Mul Test Case failed" >> $GITHUB_ENV && echo "TEST_STATUS=1" >> $GITHUB_ENV
      continue-on-error: true

    - name: Run Div Test Case
      run: |
        cd HCMUS-BigInt/build
        ./HCMUS-BigInt-Test ../../CreateTestCaseBigInt/data/div.txt || echo "Div Test Case failed" >> $GITHUB_ENV && echo "TEST_STATUS=1" >> $GITHUB_ENV
      continue-on-error: true

    - name: Run Mod Test Case
      run: |
        cd HCMUS-BigInt/build
        ./HCMUS-BigInt-Test ../../CreateTestCaseBigInt/data/mod.txt || echo "Mod Test Case failed" >> $GITHUB_ENV && echo "TEST_STATUS=1" >> $GITHUB_ENV
      continue-on-error: true

    - name: Run Pow Test Case
      run: |
        cd HCMUS-BigInt/build
        ./HCMUS-BigInt-Test ../../CreateTestCaseBigInt/data/pow.txt || echo "Pow Test Case failed" >> $GITHUB_ENV && echo "TEST_STATUS=1" >> $GITHUB_ENV
      continue-on-error: true

    - name: Check Test Status
      run: |
        if [ $TEST_STATUS -eq 1 ]; then
          echo "One or more test cases failed"
          exit 1
        fi
