name: C++ CI

on: [push, pull_request]

env:
  TEST_STATUS: 1

jobs:
  testAddFunction:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install dependencies
      run: sudo apt-get install -y g++
    - name: build
      run: |
        cd HCMUS-BigInt/build
        cmake CMakeLists.txt
        make

    - name: Run Add Test Case
      run: |
        cd HCMUS-BigInt/build
        ./HCMUS-BigInt-Test ../../CreateTestCaseBigInt/data/add.txt 
    
    - name: Run Mul Test Case
      run: |
        cd HCMUS-BigInt/build
        ./HCMUS-BigInt-Test ../../CreateTestCaseBigInt/data/mul.txt 

    - name: Run Div Test Case
      run: |
        cd HCMUS-BigInt/build
        ./HCMUS-BigInt-Test ../../CreateTestCaseBigInt/data/div.txt 

    - name: Run Mod Test Case
      run: |
        cd HCMUS-BigInt/build
        ./HCMUS-BigInt-Test ../../CreateTestCaseBigInt/data/mod.txt 

    - name: Run Pow Test Case
      run: |
        cd HCMUS-BigInt/build
        ./HCMUS-BigInt-Test ../../CreateTestCaseBigInt/data/pow.txt 

  testSubFunction:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: install dependencies
      run: sudo apt-get install -y g++
    - name: build
      run: |
        cd HCMUS-BigInt/build
        cmake CMakeLists.txt
        make

    - name: Run Sub Test Case
      run: |
        cd HCMUS-BigInt/build
        ./HCMUS-BigInt-Test ../../CreateTestCaseBigInt/data/sub.txt 
    
      