name: C++ CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install dependencies
      run: sudo apt-get install -y g++
    - name: build
      run: |
        cd HCMUS-BigInt/build
        cmake CMakeLists.txt
        make

    - name: Run Add Test Case
      run: |
        cd HCMUS-BigInt/build
        ./HCMUS-BigInt-Test ../../CreateTestCaseBigInt/data/add.txt
      continue-on-error: true

    - name: Run Sub Test Case
      run: |
        cd HCMUS-BigInt/build
        ./HCMUS-BigInt-Test ../../CreateTestCaseBigInt/data/sub.txt
      continue-on-error: true

    - name: Run Mul Test Case
      run: |
        cd HCMUS-BigInt/build
        ./HCMUS-BigInt-Test ../../CreateTestCaseBigInt/data/mul.txt
      continue-on-error: true

    - name: Run Div Test Case
      run: |
        cd HCMUS-BigInt/build
        ./HCMUS-BigInt-Test ../../CreateTestCaseBigInt/data/div.txt
      continue-on-error: true

    - name: Run Mod Test Case
      run: |
        cd HCMUS-BigInt/build
        ./HCMUS-BigInt-Test ../../CreateTestCaseBigInt/data/mod.txt
      continue-on-error: true

    - name: Run Pow Test Case
      run: |
        cd HCMUS-BigInt/build
        ./HCMUS-BigInt-Test ../../CreateTestCaseBigInt/data/pow.txt
      continue-on-error: true
